---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: probe
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-privileged-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gce:podsecuritypolicy:privileged
subjects:
- kind: ServiceAccount
  name: probe
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: default
spec:
  selector:
    matchLabels:
      name: probe
  replicas: 4
  template:
    metadata:
      labels:
        name: probe
    spec:
      serviceAccount: probe
      serviceAccountName: probe
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - probe
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: probe-container
        image: docker.io/cilium/json-mock
        livenessProbe:
          exec:
            command:
            - curl
            - "-4"
            - -sS
            - -o
            - /dev/null
            - echo.isolated.svc.cluster.local
        readinessProbe:
          exec:
            command:
            - curl
            - "-4"
            - -sS
            - -o
            - /dev/null
            - echo.isolated.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-gvisor
  namespace: default
spec:
  selector:
    matchLabels:
      name: probe-gvisor
  replicas: 2
  template:
    metadata:
      labels:
        name: probe-gvisor
    spec:
      runtimeClassName: gvisor
      serviceAccount: probe
      serviceAccountName: probe
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - probe-gvisor
              topologyKey: "kubernetes.io/hostname"
      tolerations:
        - effect: NoSchedule
          key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor
      containers:
      - name: probe-container
        image: docker.io/cilium/json-mock
        livenessProbe:
          exec:
            command:
            - curl
            - "-4"
            - -sS
            - -o
            - /dev/null
            - echo-gvisor.isolated.svc.cluster.local
        readinessProbe:
          exec:
            command:
            - curl
            - "-4"
            - -sS
            - -o
            - /dev/null
            - echo-gvisor.isolated.svc.cluster.local
