apiVersion: v1
kind: Namespace
metadata:
  name: isolated
spec: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: isolated
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: isolated
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: echo-privileged-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gce:podsecuritypolicy:privileged
subjects:
- kind: ServiceAccount
  name: echo
  namespace: isolated
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: isolated
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: isolated
spec:
  selector:
    matchLabels:
      name: echo
  replicas: 4
  template:
    metadata:
      labels:
        name: echo
    spec:
      serviceAccount: echo
      serviceAccountName: echo
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - echo
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: echo-container
        image: docker.io/cilium/json-mock
        livenessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
        readinessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
---
apiVersion: v1
kind: Service
metadata:
  name: echo-gvisor
  namespace: isolated
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: echo-gvisor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-gvisor
  namespace: isolated
spec:
  selector:
    matchLabels:
      name: echo-gvisor
  replicas: 2
  template:
    metadata:
      labels:
        name: echo-gvisor
    spec:
      runtimeClassName: gvisor
      serviceAccount: echo
      serviceAccountName: echo
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - echo-gvisor
              topologyKey: "kubernetes.io/hostname"
      tolerations:
        - effect: NoSchedule
          key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor
      containers:
      - name: echo-container
        image: docker.io/cilium/json-mock
        livenessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
        readinessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
